// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTqCtDaJHrnhdot3NKBMehmhocnxeN40o',
    appId: '1:62626873913:web:3458e9e501209178d783e8',
    messagingSenderId: '62626873913',
    projectId: 'flutter-notes-26c12',
    authDomain: 'flutter-notes-26c12.firebaseapp.com',
    storageBucket: 'flutter-notes-26c12.appspot.com',
    measurementId: 'G-K96T1T7HV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFUU8MTLQJaL7ADfKQMwrkzz07d7NmIe8',
    appId: '1:62626873913:android:84fe986c9b0ba167d783e8',
    messagingSenderId: '62626873913',
    projectId: 'flutter-notes-26c12',
    storageBucket: 'flutter-notes-26c12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChIwHBpXrhXqKH1fOO5w8bM2yxSPmO7jM',
    appId: '1:62626873913:ios:12f3b4219c6da989d783e8',
    messagingSenderId: '62626873913',
    projectId: 'flutter-notes-26c12',
    storageBucket: 'flutter-notes-26c12.appspot.com',
    iosClientId: '62626873913-plbd4hder0sfd20nd4sbpqceci609fsl.apps.googleusercontent.com',
    iosBundleId: 'vn.evolab.notes',
  );
}
